FROM golang:1.13.5 as build

#设置路径
WORKDIR /go/cache

# 设置代理
ENV GO111MODULE on
RUN echo "192.168.0.165 git.9885.net" >> /etc/hosts

RUN go env -w GOPROXY=https://goproxy.io
RUN go env -w GOPRIVATE=git.9885.net
RUN go env -w GOSUMDB=off


ADD go.mod .
ADD go.sum .
RUN go mod download

WORKDIR /go/release
ADD . .
RUN go mod tidy
RUN GOOS=linux CGO_ENABLED=0 go build -ldflags="-s -w" -installsuffix cgo -o main

FROM scratch as prod
COPY --from=build /go/release /home/app/
WORKDIR	/home/app/
EXPOSE 9000
ENTRYPOINT ["./main"]